name: Makefile CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make install

    - name: formatting 
      run: make format

    - name: run lint
      run: make lint

    - name: Run tests
      run: make test
